#!/bin/sh

start() {
    dtach -n /tmp/spoofDPI spoof-dpi -addr 192.168.1.0/8
}

stop() {
    killall spoof-dpi
}

case $1 in
    start)
	echo "start spoofDPI"
	start
    ;;
    stop)
	echo "stop spoofDPI"
	stop
    ;;
esac
