#!/bin/sh

start() {
    dtach -n /tmp/spoofDPI spoof-dpi `get_config`
}

stop() {
    killall spoof-dpi
}

get_config() {
    [ -e /opt/etc/spoofDPI/spoofDPI.conf ] && cat /opt/etc/spoofDPI/spoofDPI.conf
}

case $1 in
    start)
	echo "start spoofDPI"
	start
    ;;
    stop)
	echo "stop spoofDPI"
	stop
    ;;
esac
